
package medical_store_;
import java.sql.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.*;
import java.util.Date;
import java.time.*;

import javax.swing.table.DefaultTableModel;

public class Main_frame extends javax.swing.JFrame {

    DefaultTableModel cus_model,staff_model,med_model,short_bill_model,short_order_model;
    public Statement stmt;
    public ResultSet rs;
    public Connection con;
    public String user_id;
    
    public Main_frame(String user) 
    {
        user_id = user;
           try{  
            Class.forName("com.mysql.jdbc.Driver");    
            }
        catch(Exception e){ System.out.println(e);}  
        initComponents();
        cus_model = (DefaultTableModel)tblCustomer.getModel();
        staff_model = (DefaultTableModel)tblstaff.getModel();
        med_model = (DefaultTableModel)tblmed.getModel();
        short_bill_model=(DefaultTableModel)tblshortbill.getModel();
        short_order_model=(DefaultTableModel)tblshortorder.getModel();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        switching_panel = new javax.swing.JTabbedPane();
        your_bill = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblshortbill = new javax.swing.JTable();
        your_bill_del = new javax.swing.JButton();
        order_placed = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblshortorder = new javax.swing.JTable();
        order_del = new javax.swing.JButton();
        your_staff1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblmed = new javax.swing.JTable();
        Add_med = new javax.swing.JButton();
        Refresh_med = new javax.swing.JButton();
        med_del = new javax.swing.JButton();
        med_upd = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        Cust_add3 = new javax.swing.JLabel();
        med_price_label = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        med_t_name = new javax.swing.JTextField();
        med_drug_name = new javax.swing.JTextField();
        med_desc = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        med_valid = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        med_quantity = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        med_price = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        med_type = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        med_company_name = new javax.swing.JTextField();
        med_view_combo = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        med_expd = new javax.swing.JFormattedTextField();
        med_mfd = new javax.swing.JFormattedTextField();
        your_customer = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        Add_cust = new javax.swing.JButton();
        Refresh_cust = new javax.swing.JButton();
        cust_del = new javax.swing.JButton();
        cust_upd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Cust_add = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cust_l_name = new javax.swing.JTextField();
        cust_f_name = new javax.swing.JTextField();
        cust_addres = new javax.swing.JTextField();
        cust_contact_no = new javax.swing.JTextField();
        cust_valid = new javax.swing.JLabel();
        your_staff = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblstaff = new javax.swing.JTable();
        Add_staff = new javax.swing.JButton();
        Refresh_staff = new javax.swing.JButton();
        staff_del = new javax.swing.JButton();
        staff_upd = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Cust_add2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        staff_l_name = new javax.swing.JTextField();
        staff_f_name = new javax.swing.JTextField();
        staff_aadhar = new javax.swing.JTextField();
        staff_contact_no = new javax.swing.JTextField();
        staff_valid = new javax.swing.JLabel();
        staff_admin_rights = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        staff_pass = new javax.swing.JTextField();
        generate_bill = new javax.swing.JButton();
        receive_order = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        staff_welcome_name = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Medical Store");
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        switching_panel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        switching_panel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                switching_panelMouseClicked(evt);
            }
        });

        tblshortbill.setAutoCreateRowSorter(true);
        tblshortbill.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill id", "Bill Date", "Customer Name", "Product Names", "Total Amount", "Doctor Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblshortbill.setToolTipText("");
        tblshortbill.setAutoscrolls(false);
        tblshortbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblshortbillMouseClicked(evt);
            }
        });
        tblshortbill.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblshortbillKeyPressed(evt);
            }
        });
        jScrollPane6.setViewportView(tblshortbill);
        tblshortbill.getColumnModel().getColumn(3).setPreferredWidth(350);

        your_bill_del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        your_bill_del.setText("Delete");
        your_bill_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                your_bill_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout your_billLayout = new javax.swing.GroupLayout(your_bill);
        your_bill.setLayout(your_billLayout);
        your_billLayout.setHorizontalGroup(
            your_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(your_billLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(your_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1344, Short.MAX_VALUE)
                    .addGroup(your_billLayout.createSequentialGroup()
                        .addComponent(your_bill_del)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        your_billLayout.setVerticalGroup(
            your_billLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(your_billLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(your_bill_del)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        switching_panel.addTab("Your bills", your_bill);

        tblshortorder.setAutoCreateRowSorter(true);
        tblshortorder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order id", "Order Date", "Recieved By", "Product Names", "Total Amount", "Agent Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblshortorder.setToolTipText("");
        tblshortorder.setAutoscrolls(false);
        tblshortorder.setRowSorter(null);
        tblshortorder.setUpdateSelectionOnSort(false);
        tblshortorder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblshortorderMouseClicked(evt);
            }
        });
        tblshortorder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblshortorderKeyPressed(evt);
            }
        });
        jScrollPane7.setViewportView(tblshortorder);
        tblshortorder.getColumnModel().getColumn(3).setPreferredWidth(350);

        order_del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        order_del.setText("Delete");
        order_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                order_delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout order_placedLayout = new javax.swing.GroupLayout(order_placed);
        order_placed.setLayout(order_placedLayout);
        order_placedLayout.setHorizontalGroup(
            order_placedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(order_placedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(order_placedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1344, Short.MAX_VALUE)
                    .addGroup(order_placedLayout.createSequentialGroup()
                        .addComponent(order_del)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        order_placedLayout.setVerticalGroup(
            order_placedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(order_placedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(order_del)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        switching_panel.addTab("Orders Placed", order_placed);

        tblmed.setAutoCreateRowSorter(true);
        tblmed.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Name", "Trade Name", "Description", "Price", "Quantity", "Mfd", "Expd", "Type", "Company Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblmed.setToolTipText("");
        tblmed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblmedMouseClicked(evt);
            }
        });
        tblmed.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblmedKeyPressed(evt);
            }
        });
        jScrollPane5.setViewportView(tblmed);

        Add_med.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Add_med.setText("Add Medicine");
        Add_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_medActionPerformed(evt);
            }
        });

        Refresh_med.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Refresh_med.setText("Refresh");
        Refresh_med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_medActionPerformed(evt);
            }
        });

        med_del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_del.setText("Delete");
        med_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_delActionPerformed(evt);
            }
        });

        med_upd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_upd.setText("Update");
        med_upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_updActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Drug Name :");

        Cust_add3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cust_add3.setText("Mfd :");

        med_price_label.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_price_label.setText("Price :");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Trade Name :");

        med_t_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_t_nameActionPerformed(evt);
            }
        });

        med_drug_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_drug_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_drug_nameActionPerformed(evt);
            }
        });

        med_desc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_descActionPerformed(evt);
            }
        });

        jLabel17.setText("jLabel1");

        med_valid.setForeground(new java.awt.Color(255, 0, 0));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Type :");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Description :");

        med_quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_quantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_quantityActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Quantity :");

        med_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_priceActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Expd :");

        med_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_typeActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("View Type :");

        med_company_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_company_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_company_nameActionPerformed(evt);
            }
        });

        med_view_combo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_view_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Active Medicines", "Expired Medicines" }));
        med_view_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                med_view_comboItemStateChanged(evt);
            }
        });
        med_view_combo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                med_view_comboMouseClicked(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Company Name :");

        try {
            med_expd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        med_expd.setToolTipText("");
        med_expd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_expd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_expdActionPerformed(evt);
            }
        });

        try {
            med_mfd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        med_mfd.setToolTipText("");
        med_mfd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_mfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_mfdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout your_staff1Layout = new javax.swing.GroupLayout(your_staff1);
        your_staff1.setLayout(your_staff1Layout);
        your_staff1Layout.setHorizontalGroup(
            your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(your_staff1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(your_staff1Layout.createSequentialGroup()
                        .addComponent(Add_med)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Refresh_med)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(med_del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(med_upd)
                        .addGap(371, 371, 371)
                        .addComponent(med_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(your_staff1Layout.createSequentialGroup()
                        .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(your_staff1Layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(med_drug_name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(med_t_name, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(med_desc, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(your_staff1Layout.createSequentialGroup()
                                .addComponent(Cust_add3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(med_mfd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(med_expd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(med_type, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23)))
                        .addGap(4, 4, 4)
                        .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(your_staff1Layout.createSequentialGroup()
                                .addComponent(med_company_name, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(jLabel22))
                            .addGroup(your_staff1Layout.createSequentialGroup()
                                .addComponent(med_price_label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(med_price, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)))
                        .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(your_staff1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(med_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(your_staff1Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel17)
                                    .addComponent(med_view_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)))
                .addContainerGap())
        );
        your_staff1Layout.setVerticalGroup(
            your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(your_staff1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Add_med, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Refresh_med)
                        .addComponent(med_del)
                        .addComponent(med_upd))
                    .addComponent(med_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(med_price_label, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(med_t_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(med_drug_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(med_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(med_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(med_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(your_staff1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(med_view_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Cust_add3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med_company_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med_expd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(med_mfd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(your_staff1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(your_staff1Layout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, your_staff1Layout.createSequentialGroup()
                        .addGap(435, 435, 435)
                        .addComponent(jLabel17)
                        .addContainerGap())))
        );

        cust_valid.setVisible(false);

        switching_panel.addTab("Medicine list", your_staff1);

        tblCustomer.setAutoCreateRowSorter(true);
        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact No.", "Address"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.setToolTipText("");
        tblCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCustomerMouseClicked(evt);
            }
        });
        tblCustomer.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblCustomerKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblCustomer);

        Add_cust.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Add_cust.setText("Add Customer");
        Add_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_custActionPerformed(evt);
            }
        });

        Refresh_cust.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Refresh_cust.setText("Refresh");
        Refresh_cust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_custActionPerformed(evt);
            }
        });

        cust_del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cust_del.setText("Delete");
        cust_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_delActionPerformed(evt);
            }
        });

        cust_upd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cust_upd.setText("Update");
        cust_upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_updActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("First Name :");

        Cust_add.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cust_add.setText("Address : ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contact No :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Last Name :");

        cust_l_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cust_l_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_l_nameActionPerformed(evt);
            }
        });

        cust_f_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cust_f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cust_f_nameActionPerformed(evt);
            }
        });

        cust_addres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cust_contact_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cust_valid.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout your_customerLayout = new javax.swing.GroupLayout(your_customer);
        your_customer.setLayout(your_customerLayout);
        your_customerLayout.setHorizontalGroup(
            your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(your_customerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(your_customerLayout.createSequentialGroup()
                        .addGroup(your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(your_customerLayout.createSequentialGroup()
                                .addComponent(Add_cust)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Refresh_cust)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cust_del))
                            .addGroup(your_customerLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cust_f_name, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(your_customerLayout.createSequentialGroup()
                                .addComponent(cust_upd)
                                .addGap(339, 339, 339))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, your_customerLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cust_l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cust_contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 291, Short.MAX_VALUE))
                    .addGroup(your_customerLayout.createSequentialGroup()
                        .addComponent(Cust_add)
                        .addGap(18, 18, 18)
                        .addComponent(cust_addres, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cust_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        your_customerLayout.setVerticalGroup(
            your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(your_customerLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Add_cust)
                    .addComponent(Refresh_cust)
                    .addComponent(cust_del)
                    .addComponent(cust_upd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cust_l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cust_f_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cust_contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(your_customerLayout.createSequentialGroup()
                        .addGroup(your_customerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Cust_add, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cust_addres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(your_customerLayout.createSequentialGroup()
                        .addComponent(cust_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        cust_valid.setVisible(false);

        switching_panel.addTab("Your customer", your_customer);

        tblstaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Contact No.", "Aadhar No."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblstaff.setToolTipText("");
        tblstaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblstaffMouseClicked(evt);
            }
        });
        tblstaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblstaffKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(tblstaff);

        Add_staff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Add_staff.setText("Add Staff");
        Add_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Add_staffActionPerformed(evt);
            }
        });

        Refresh_staff.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Refresh_staff.setText("Refresh");
        Refresh_staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Refresh_staffActionPerformed(evt);
            }
        });

        staff_del.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staff_del.setText("Delete");
        staff_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_delActionPerformed(evt);
            }
        });

        staff_upd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staff_upd.setText("Update");
        staff_upd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_updActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("First Name :");

        Cust_add2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Cust_add2.setText("Aadhar No  : ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Contact No :");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Last Name :");

        staff_l_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staff_l_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_l_nameActionPerformed(evt);
            }
        });

        staff_f_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staff_f_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_f_nameActionPerformed(evt);
            }
        });

        staff_aadhar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        staff_contact_no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        staff_valid.setForeground(new java.awt.Color(255, 0, 0));

        staff_admin_rights.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staff_admin_rights.setText("Admin rights");
        staff_admin_rights.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_admin_rightsActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Password :");

        staff_pass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        staff_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staff_passActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout your_staffLayout = new javax.swing.GroupLayout(your_staff);
        your_staff.setLayout(your_staffLayout);
        your_staffLayout.setHorizontalGroup(
            your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(your_staffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(your_staffLayout.createSequentialGroup()
                        .addComponent(Add_staff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Refresh_staff)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staff_del)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staff_upd)
                        .addGap(371, 371, 371)
                        .addComponent(staff_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(your_staffLayout.createSequentialGroup()
                        .addGroup(your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(your_staffLayout.createSequentialGroup()
                                .addComponent(Cust_add2)
                                .addGap(18, 18, 18)
                                .addComponent(staff_aadhar, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(your_staffLayout.createSequentialGroup()
                                .addGroup(your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(your_staffLayout.createSequentialGroup()
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(staff_f_name, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(staff_l_name, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(your_staffLayout.createSequentialGroup()
                                        .addGap(431, 431, 431)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(staff_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(staff_contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(staff_admin_rights))))
                        .addGap(0, 291, Short.MAX_VALUE)))
                .addContainerGap())
        );
        your_staffLayout.setVerticalGroup(
            your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(your_staffLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Add_staff, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Refresh_staff)
                        .addComponent(staff_del)
                        .addComponent(staff_upd))
                    .addComponent(staff_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_l_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_f_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_contact_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(your_staffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cust_add2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_aadhar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_admin_rights)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(staff_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cust_valid.setVisible(false);

        switching_panel.addTab("Your staff", your_staff);

        generate_bill.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        generate_bill.setText("Generate Bill");
        generate_bill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generate_billActionPerformed(evt);
            }
        });

        receive_order.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        receive_order.setText("Receive Order");
        receive_order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receive_orderActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medical_store_/Picture3.png"))); // NOI18N
        jLabel1.setToolTipText("");

        staff_welcome_name.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        staff_welcome_name.setText("Tony Stark");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("Welcome,");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(staff_welcome_name)
                        .addGap(93, 93, 93)
                        .addComponent(generate_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(receive_order, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(switching_panel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(staff_welcome_name)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(generate_bill, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(receive_order, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(switching_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void get_cust_db() { 
        try{
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");  
            stmt=con.createStatement();
            rs = stmt.executeQuery("select * from Customer;");  
            cus_model.setRowCount(0);
            while(rs.next())  
                cus_model.insertRow(cus_model.getRowCount(), new Object[]{rs.getString(2),Long.parseLong(rs.getString(3)),rs.getString(4)});

              con.close();
        }catch(Exception e){ System.out.println(e);}  
    }     
    
    private void get_staff_db() {
    int i; 
        try{
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");  
            stmt=con.createStatement();
            rs = stmt.executeQuery("select Name,Contact_no,Adhar_no From staff;");  
            staff_model.setRowCount(0);
            while(rs.next())  
                staff_model.insertRow(staff_model.getRowCount(), new Object[]{rs.getString(1),Long.parseLong(rs.getString(2)),Long.parseLong(rs.getString(3))});

              con.close();
        }catch(Exception e){ System.out.println(e);}  
    }     
    
    private void get_med_db() {
        try{
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");  
            stmt=con.createStatement();
            int index=med_view_combo.getSelectedIndex();
            if(index==2)
                {rs = stmt.executeQuery("select * From Expired_medicine order by drug_name;"); }
            else if(index==1)
                {rs = stmt.executeQuery("select * From Active_medicine order by drug_name;");  }
            else
                {rs = stmt.executeQuery("select * From Medicine_list order by drug_name;"); }
            med_model.setRowCount(0);
            Date mfd_sql=new Date();
            Date expd_sql=new Date();
            String mfd_date="";
            String expd_date="";
            while(rs.next())  
            { 
                mfd_sql=new SimpleDateFormat("yyyy-MM-dd").parse(rs.getString(7));
                expd_sql=new SimpleDateFormat("yyyy-MM-dd").parse(rs.getString(8));
                SimpleDateFormat dmyFormat = new SimpleDateFormat("dd/MM/yyyy");
                mfd_date = dmyFormat.format(mfd_sql);
                expd_date = dmyFormat.format(expd_sql);
                med_model.insertRow(med_model.getRowCount(), new Object[]{rs.getString(2),rs.getString(3),rs.getString(4),Long.parseLong(rs.getString(5)),Long.parseLong(rs.getString(6)),mfd_date,expd_date,rs.getString(9),rs.getString(10)});
            }
              con.close();
        }catch(Exception e){ System.out.println(e);}  
    }
    
    private void get_short_bill() {
        try{
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");  
            stmt=con.createStatement();
            rs = stmt.executeQuery("call short_bill();"); 
            short_bill_model.setRowCount(0);
            while(rs.next())  
                short_bill_model.insertRow(short_bill_model.getRowCount(), new Object[]{Long.parseLong(rs.getString(1)),rs.getString(2),rs.getString(3),rs.getString(4),Long.parseLong(rs.getString(5)),rs.getString(6)});
              con.close();
        }catch(Exception e){ System.out.println(e);}  
    }
    
    private void get_short_order() {
        try{
            con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");  
            stmt=con.createStatement();
            rs = stmt.executeQuery("call short_order();"); 
            short_order_model.setRowCount(0);
            while(rs.next())  
                short_order_model.insertRow(short_order_model.getRowCount(), new Object[]{Long.parseLong(rs.getString(1)),rs.getString(2),rs.getString(3),rs.getString(4),Long.parseLong(rs.getString(5)),rs.getString(6)});
              con.close();
        }catch(Exception e){ System.out.println(e);}  
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
       System.out.println(user_id);
    }//GEN-LAST:event_formComponentShown

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        switching_panel.setEnabled(true);
        get_cust_db();
        get_staff_db();
        get_med_db();
        get_short_bill();
        get_short_order();
    }//GEN-LAST:event_formWindowGainedFocus

    private void switching_panelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_switching_panelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_switching_panelMouseClicked

    private int Cust_TextValidation(){
        
        cust_valid.setVisible(false);
        
        String name1 =  cust_f_name.getText();
        if(name1 == null || name1.isEmpty()) {
        cust_valid.setVisible(true);
        cust_valid.setText("First Name. cannot be blank.");
        return 0;
        }
        
        String name =  cust_l_name.getText();
        if(name == null || name.isEmpty()) {
        cust_valid.setVisible(true);
        cust_valid.setText("Last Name. cannot be blank.");
        return 0;
        }
        
        String phn =  cust_contact_no.getText();
        if(phn == null || phn.isEmpty()) {
        cust_valid.setVisible(true);
        cust_valid.setText("Phone no. cannot be blank.");
        return 0;
        }
        else if(phn.length()!=10)
        {
            cust_valid.setVisible(true);
            cust_valid.setText("Enter a valid No.");
            return 0;
        }
       
        try  
       {  
         long phn_no = Long.parseLong(phn);  
       }  
       catch(NumberFormatException nfe)  
       {  
         cust_valid.setVisible(true);
         cust_valid.setText("Enter a valid No.");
         return 0;
       }
        
       String add =  cust_addres.getText();
        if(add == null || add.isEmpty()) {
        cust_valid.setVisible(true);
        cust_valid.setText("Address cannot be blank.");
        return 0;
        }
        
        return 1;
    }
    
    private int Staff_TextValidation(){
        
        staff_valid.setVisible(false);
        
        String name1 =  staff_f_name.getText();
        if(name1 == null || name1.isEmpty()) {
        staff_valid.setVisible(true);
        staff_valid.setText("First Name. cannot be blank.");
        return 0;
        }
        
        String name =  staff_l_name.getText();
        if(name == null || name.isEmpty()) {
        staff_valid.setVisible(true);
        staff_valid.setText("Last Name. cannot be blank.");
        return 0;
        }
        
        String phn =  staff_contact_no.getText();
        if(phn == null || phn.isEmpty()) {
        staff_valid.setVisible(true);
        staff_valid.setText("Mobile no. cannot be blank.");
        return 0;
        }
        else if(phn.length()!=10)
        {
            staff_valid.setVisible(true);
            staff_valid.setText("Enter a valid Mobile No.");
            return 0;
        }
       
        try  
       {  
         long phn_no = Long.parseLong(phn);  
       }  
       catch(NumberFormatException nfe)  
       {  
         staff_valid.setVisible(true);
         staff_valid.setText("Enter a valid Mobile No.");
         return 0;
       }
        
       String aadhar =  staff_aadhar.getText();
        if(aadhar == null || aadhar.isEmpty()) {
        staff_valid.setVisible(true);
        staff_valid.setText("Aadhar No. cannot be blank.");
        return 0;
        }
        else if(aadhar.length()!=12)
        {
            staff_valid.setVisible(true);
            staff_valid.setText("Enter a valid Aadhar No.");
            return 0;
        }
       
        try  
       {  
         long phn_no = Long.parseLong(aadhar);  
       }  
       catch(NumberFormatException nfe)  
       {  
         staff_valid.setVisible(true);
         staff_valid.setText("Enter a valid Aadhar No.");
         return 0;
       }
        
        String pass =  staff_pass.getText();
        if(pass == null || pass.isEmpty()) {
        staff_valid.setVisible(true);
        staff_valid.setText("Password cannot be blank.");
        return 0;
        }
        
       int exist =0;
       String ad_exist_name="";
       
       try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();        
                rs = stmt.executeQuery("select Name from staff where Adhar_no = "+aadhar+";");  
                while(rs.next())  
                {
                    ad_exist_name = rs.getString("Name");
                    exist++;
                }
                if(!(aadhar).equals(String.valueOf(staff_model.getValueAt(tblstaff.getSelectedRow(), 2))))
                {   if(exist>0)
                    {
                        staff_valid.setVisible(true);
                        staff_valid.setText("Aadhar No. is already registered For staff : "+ad_exist_name);
                        return 0;
                    }
                }
                con.close();
            }catch(Exception e){ System.out.println(e);}

        
        return 1;
    }
    
    private int Med_TextValidation()
    {
        med_valid.setVisible(false);
        
        String name =  med_drug_name.getText();
        if(name == null || name.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Drug Name. cannot be blank.");
        return 0;
        }
        
        
        String price =  med_price.getText();
        if(price == null || price.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Price cannot be blank.");
        return 0;
        }
        try  
       {  
         int price_dummy = Integer.parseInt(price); 
         if(price_dummy<=0)
         {
             med_valid.setVisible(true);
             med_valid.setText("Price cannot be equal or less than Zero.");
             return 0;
         }
       }  
       catch(NumberFormatException nfe)  
       {  
         med_valid.setVisible(true);
         med_valid.setText("Enter a valid price.");
         return 0;
       }
        
        String quantity =  med_quantity.getText();
        if(quantity == null || quantity.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Quantity cannot be blank.");
        return 0;
        }
        try  
       {  
         int quantity_dummy = Integer.parseInt(quantity); 
         if(quantity_dummy<0)
         {
             med_valid.setVisible(true);
             med_valid.setText("Quantity cannot be less than Zero.");
             return 0;
         }
       }  
       catch(NumberFormatException nfe)  
       {  
         med_valid.setVisible(true);
         med_valid.setText("Enter a valid Quantity.");
         return 0;
       }
        
        
       String mfd =  med_expd.getText();
       Date mfd_date=new Date();
       Date expd_date=new Date();
        try  
       {  
         mfd_date=new SimpleDateFormat("dd/MM/yyyy").parse(mfd);
       }  
       catch(Exception e)  
       {  
         System.out.println(e);
         med_valid.setVisible(true);
         med_valid.setText("Enter a valid Manufacture Date.");
         return 0;
       }
        
        String expd =  med_expd.getText();
        try  
       {  
         expd_date=new SimpleDateFormat("dd/MM/yyyy").parse(expd);
       }  
       catch(Exception e)  
       {  
         med_valid.setText("Enter a valid Expiry Date.");
         System.out.println(e);
         med_valid.setVisible(true);
         return 0;
       }
        
        if(mfd_date.after(expd_date))
        {
            med_valid.setVisible(true);
            med_valid.setText("Expiry Date cannot be before than Manufacturing Date.");
            return 0;
        }
                
        String type =  med_type.getText();
        if(type == null || type.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Medicine Type cannot be blank.");
        return 0;
        }
        
        String comp_name =  med_company_name.getText();
        if(comp_name == null || comp_name.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Company Name cannot be blank.");
        return 0;
        }
        
        return 1;
    }
    private void Cust_delete()
    {
        if(tblCustomer.getSelectedRow()!=-1){
            String Name = String.valueOf(cus_model.getValueAt(tblCustomer.getSelectedRow(), 0));
            String mobile_no = String.valueOf(cus_model.getValueAt(tblCustomer.getSelectedRow(), 1));
            try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                stmt.executeUpdate("delete from customer where Name ='"+Name+"' And Contact_No = "+mobile_no+";");
                con.close();
            }catch(Exception e){ System.out.println(e);}
            cus_model.removeRow(tblCustomer.getSelectedRow());
        }
    }
    
    private void Staff_delete()
    {
        if(tblstaff.getSelectedRow()!=-1){
            String Aadhar = String.valueOf(staff_model.getValueAt(tblstaff.getSelectedRow(), 2));
            try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                stmt.executeUpdate("delete from staff where Adhar_no = "+Aadhar+";");
                con.close();
            }catch(Exception e){ System.out.println(e);}
            staff_model.removeRow(tblstaff.getSelectedRow());
        }
    }
    
    private void Med_delete()
    {
        if(tblmed.getSelectedRow()!=-1){
            String drug_name = String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 0));
            String Type = String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 7));
            
            try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                stmt.executeUpdate("delete from medicine_list where Drug_Name = '"+drug_name+"' And Medicine_form= '"+Type+"';");
                con.close();
            }catch(Exception e){ System.out.println(e);}
            med_model.removeRow(tblmed.getSelectedRow());
        }
           
    }
    
  private void bill_short_delete()
    {
        if(tblshortbill.getSelectedRow()!=-1){
            String id = String.valueOf(short_bill_model.getValueAt(tblshortbill.getSelectedRow(), 0));
            try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                stmt.executeUpdate("delete from bill where b_id = "+id+";");
                con.close();
            }catch(Exception e){ System.out.println(e);}
            short_bill_model.removeRow(tblshortbill.getSelectedRow());
        }
    }
  private void order_short_delete()
    {
        if(tblshortorder.getSelectedRow()!=-1){
            String id = String.valueOf(short_order_model.getValueAt(tblshortorder.getSelectedRow(), 0));
            try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                stmt.executeUpdate("delete from orders where order_id = "+id+";");
                con.close();
            }catch(Exception e){ System.out.println(e);}
            short_order_model.removeRow(tblshortorder.getSelectedRow());
        }
    }
    
    private void cust_updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_updActionPerformed
       if(tblCustomer.getSelectedRow()!=-1){
          
        if(Cust_TextValidation()==1)
        {
             Cust_delete();
            String name1 =  cust_f_name.getText();
            String name =  cust_l_name.getText();
            long phn_no = Long.parseLong(cust_contact_no.getText());
            String address = cust_addres.getText().replace('\n', ',');
            
            cust_f_name.setText("");
            cust_l_name.setText("");
            cust_contact_no.setText("");
            cust_addres .setText("");    
        
            try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");  
                stmt=con.createStatement();
                
                long millis = System.currentTimeMillis();
                System.out.println("i sm vd");
                stmt.executeUpdate("INSERT INTO Customer VALUES('"+name1.substring(0,1).toUpperCase()+ name.substring(0,1).toUpperCase()+millis+"','"+name1+ " "+name+"',"+phn_no+",'"+address+"');");  
                con.close();
                System.out.println(millis);
            }catch(Exception e){ System.out.println(e);}  
            
            
            get_cust_db();
        }
       }
    }//GEN-LAST:event_cust_updActionPerformed
    
    
    private void cust_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_delActionPerformed
        Cust_delete();
    }//GEN-LAST:event_cust_delActionPerformed

    private void Refresh_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_custActionPerformed
        get_cust_db();
    }//GEN-LAST:event_Refresh_custActionPerformed

    private void Add_custActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_custActionPerformed
        switching_panel.setEnabled(false);
        new New_cust().setVisible(true);
    }//GEN-LAST:event_Add_custActionPerformed

    private void cust_f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_f_nameActionPerformed

    private void tblCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCustomerMouseClicked
        String name = String.valueOf(cus_model.getValueAt(tblCustomer.getSelectedRow(), 0));
        cust_f_name.setText(name.substring(0, name.indexOf(" ")));
        cust_l_name.setText(name.substring(name.indexOf(" ")+1));
        cust_contact_no.setText(String.valueOf(cus_model.getValueAt(tblCustomer.getSelectedRow(), 1)));
        cust_addres.setText(String.valueOf(cus_model.getValueAt(tblCustomer.getSelectedRow(), 2)));
            
        
    }//GEN-LAST:event_tblCustomerMouseClicked

    private void cust_l_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cust_l_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cust_l_nameActionPerformed

    private void tblCustomerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblCustomerKeyPressed

    }//GEN-LAST:event_tblCustomerKeyPressed

    private void tblstaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblstaffMouseClicked
        String name = String.valueOf(staff_model.getValueAt(tblstaff.getSelectedRow(), 0));
        String Aadhar = String.valueOf(staff_model.getValueAt(tblstaff.getSelectedRow(), 2));
        int is_admin=0;
        
        
        staff_f_name.setText(name.substring(0, name.indexOf(" ")));
        staff_l_name.setText(name.substring(name.indexOf(" ")+1));
        staff_contact_no.setText(String.valueOf(staff_model.getValueAt(tblstaff.getSelectedRow(), 1)));
        staff_aadhar.setText(Aadhar);
        
            try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                rs = stmt.executeQuery("select password,is_admin from staff where Adhar_no = "+Aadhar+";");  
                while(rs.next())  
                {
                    staff_pass.setText(rs.getString(1));
                    is_admin=Integer.parseInt(rs.getString(2));
                }
                
                staff_admin_rights.setSelected(is_admin > 0 ? true : false );
                con.close();
            }catch(Exception e){ System.out.println(e);}
        
    }//GEN-LAST:event_tblstaffMouseClicked

    private void tblstaffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblstaffKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblstaffKeyPressed

    private void Add_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_staffActionPerformed
      new New_staff().setVisible(true);
    }//GEN-LAST:event_Add_staffActionPerformed

    private void Refresh_staffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_staffActionPerformed
        get_staff_db();
    }//GEN-LAST:event_Refresh_staffActionPerformed

    private void staff_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_delActionPerformed
        Staff_delete();
    }//GEN-LAST:event_staff_delActionPerformed

    private void staff_updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_updActionPerformed
      
        if(tblstaff.getSelectedRow()!=-1){
          
           
        if(Staff_TextValidation()==1)
        {
              Staff_delete();
            String name1 =  staff_f_name.getText();
            String name =  staff_l_name.getText();
            long phn_no = Long.parseLong(staff_contact_no.getText());
            String aadhar = staff_aadhar.getText();
            String Password = staff_pass.getText();
            boolean check_admin = staff_admin_rights.isSelected();
            String admin;
            if(check_admin==true)
            {
                admin = "TRUE";
            }
            else
            {
                admin = "FALSE";
            }
            
            staff_f_name.setText("");
            staff_l_name.setText("");
            staff_contact_no.setText("");
            staff_aadhar .setText(""); 
            staff_pass.setText("");
            staff_admin_rights.setSelected(false);
        
            try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");  
                stmt=con.createStatement();
                
                long millis = System.currentTimeMillis();
                stmt.executeUpdate("INSERT INTO Staff VALUES('"+name1.substring(0,1).toUpperCase()+ name.substring(0,1).toUpperCase()+millis+"','"+name1+ " "+name+"',"+phn_no+",'"+Password+"',"+aadhar+","+admin+");");
                con.close();
            }catch(Exception e){ System.out.println(e);}  
            
            
            get_staff_db();
        }
       } 
    }//GEN-LAST:event_staff_updActionPerformed

    private void staff_l_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_l_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_l_nameActionPerformed

    private void staff_f_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_f_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_f_nameActionPerformed

    private void staff_admin_rightsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_admin_rightsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_admin_rightsActionPerformed

    private void staff_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staff_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staff_passActionPerformed

    private void tblmedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblmedMouseClicked
        
        med_drug_name.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 0)));
        med_t_name.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 1)));
        med_desc.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 2)));
        med_price.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 3)));
        med_quantity.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 4)));        
        med_mfd.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 5)));
        med_expd.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 6)));
        med_type.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 7)));
        med_company_name.setText(String.valueOf(med_model.getValueAt(tblmed.getSelectedRow(), 8)));   
    }//GEN-LAST:event_tblmedMouseClicked

    private void tblmedKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblmedKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblmedKeyPressed

    private void Add_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Add_medActionPerformed
        new New_medicine().setVisible(true);
    }//GEN-LAST:event_Add_medActionPerformed

    private void Refresh_medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Refresh_medActionPerformed
        get_med_db();
    }//GEN-LAST:event_Refresh_medActionPerformed

    private void med_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_delActionPerformed
      Med_delete();
    }//GEN-LAST:event_med_delActionPerformed

    private void med_updActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_updActionPerformed
        if(tblmed.getSelectedRow()!=-1){
          
        if(Med_TextValidation()==1)
        {
           Med_delete();
            
           String name =  med_drug_name.getText();
           String t_name =  med_t_name.getText();
           String desc =  med_desc.getText();
           String price =  med_price.getText();
           String quantity =  med_quantity.getText();
           String mfd =  med_expd.getText(); 
           String expd =  med_expd.getText();
            
           String mfd_sql="";
           String expd_sql="";
            try  
            {  
              Date mfd_date=new SimpleDateFormat("dd/MM/yyyy").parse(mfd);
              Date expd_date=new SimpleDateFormat("dd/MM/yyyy").parse(expd);
              SimpleDateFormat dmyFormat = new SimpleDateFormat("yyyy-MM-dd");
              mfd_sql = dmyFormat.format(mfd_date);
              expd_sql = dmyFormat.format(expd_date);
            }  
            catch(Exception e)  
            {  
              System.out.println(e);
            }
            
            String type =  med_type.getText();
            String comp_name =  med_company_name.getText();
            
            try{
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                rs = stmt.executeQuery("select max(Product_id)+1 as id from medicine_list;");  
                String id="";
                while(rs.next())  
                {
                    id = rs.getString("id");
                }
                stmt.executeUpdate("INSERT INTO Medicine_list VALUES("+id+",'"+name+"','"+t_name+ "','"+desc+"',"+price+","+quantity+",'"+mfd_sql+"','"+expd_sql+"','"+type+"','"+comp_name+"');");
                con.close();
                
            }catch(Exception e){ System.out.println(e);}

            med_drug_name.setText("");
            med_t_name.setText("");
            med_desc.setText("");
            med_price.setText("");
            med_quantity.setText("");
            med_expd.setText("");
            med_expd.setText("");
            med_type.setText("");
            med_company_name.setText("");
         
            get_med_db();
        }
       }
    }//GEN-LAST:event_med_updActionPerformed

    private void med_t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_t_nameActionPerformed

    private void med_drug_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_drug_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_drug_nameActionPerformed

    private void med_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_descActionPerformed

    private void med_quantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_quantityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_quantityActionPerformed

    private void med_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_priceActionPerformed

    private void med_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_typeActionPerformed

    private void med_company_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_company_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_company_nameActionPerformed

    private void med_view_comboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_med_view_comboMouseClicked

    }//GEN-LAST:event_med_view_comboMouseClicked

    private void med_view_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_med_view_comboItemStateChanged
        get_med_db();
    }//GEN-LAST:event_med_view_comboItemStateChanged

    private void med_mfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_mfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_mfdActionPerformed

    private void tblshortbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblshortbillMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblshortbillMouseClicked

    private void tblshortbillKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblshortbillKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblshortbillKeyPressed

    private void your_bill_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_your_bill_delActionPerformed
        bill_short_delete();
    }//GEN-LAST:event_your_bill_delActionPerformed

    private void tblshortorderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblshortorderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblshortorderMouseClicked

    private void tblshortorderKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblshortorderKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tblshortorderKeyPressed

    private void order_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_order_delActionPerformed
        order_short_delete();
    }//GEN-LAST:event_order_delActionPerformed

    private void med_expdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_expdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_expdActionPerformed

    private void generate_billActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generate_billActionPerformed
       new bill_desc().setVisible(true);
    }//GEN-LAST:event_generate_billActionPerformed

    private void receive_orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receive_orderActionPerformed
       new order_desc().setVisible(true);
    }//GEN-LAST:event_receive_orderActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       
        int is_admin=1;
        String name ="";
         try{
                con=DriverManager.getConnection(  "jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                rs = stmt.executeQuery("select is_admin,Name from staff where Staff_id = '"+user_id+"';");  
                while(rs.next())  
                {
                    
                    is_admin=Integer.parseInt(rs.getString(1));
                    name = rs.getString(2);
                }
                con.close();
            }catch(Exception e){ System.out.println(e);}
         
        if(is_admin < 1 ) 
        {
//            bill_modify.setVisible(false);
           your_bill_del.setVisible(false);
           order_del.setVisible(false);
  //         order_modify.setVisible(false);
           staff_del.setVisible(false);
           staff_upd.setVisible(false);
           Refresh_staff.setVisible(false);
           Add_staff.setVisible(false);
           jLabel13.setVisible(false);
           staff_pass.setVisible(false);
           staff_admin_rights.setVisible(false);
        }
        
        staff_welcome_name.setText(name);
    }//GEN-LAST:event_formWindowOpened

   
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_frame("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add_cust;
    private javax.swing.JButton Add_med;
    private javax.swing.JButton Add_staff;
    private javax.swing.JLabel Cust_add;
    private javax.swing.JLabel Cust_add2;
    private javax.swing.JLabel Cust_add3;
    private javax.swing.JButton Refresh_cust;
    private javax.swing.JButton Refresh_med;
    private javax.swing.JButton Refresh_staff;
    private javax.swing.JTextField cust_addres;
    private javax.swing.JTextField cust_contact_no;
    private javax.swing.JButton cust_del;
    private javax.swing.JTextField cust_f_name;
    private javax.swing.JTextField cust_l_name;
    private javax.swing.JButton cust_upd;
    private javax.swing.JLabel cust_valid;
    private javax.swing.JButton generate_bill;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextField med_company_name;
    private javax.swing.JButton med_del;
    private javax.swing.JTextField med_desc;
    private javax.swing.JTextField med_drug_name;
    private javax.swing.JFormattedTextField med_expd;
    private javax.swing.JFormattedTextField med_mfd;
    private javax.swing.JTextField med_price;
    private javax.swing.JLabel med_price_label;
    private javax.swing.JTextField med_quantity;
    private javax.swing.JTextField med_t_name;
    private javax.swing.JTextField med_type;
    private javax.swing.JButton med_upd;
    private javax.swing.JLabel med_valid;
    private javax.swing.JComboBox<String> med_view_combo;
    private javax.swing.JButton order_del;
    private javax.swing.JPanel order_placed;
    private javax.swing.JButton receive_order;
    private javax.swing.JTextField staff_aadhar;
    private javax.swing.JCheckBox staff_admin_rights;
    private javax.swing.JTextField staff_contact_no;
    private javax.swing.JButton staff_del;
    private javax.swing.JTextField staff_f_name;
    private javax.swing.JTextField staff_l_name;
    private javax.swing.JTextField staff_pass;
    private javax.swing.JButton staff_upd;
    private javax.swing.JLabel staff_valid;
    private javax.swing.JLabel staff_welcome_name;
    private javax.swing.JTabbedPane switching_panel;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTable tblmed;
    private javax.swing.JTable tblshortbill;
    private javax.swing.JTable tblshortorder;
    private javax.swing.JTable tblstaff;
    private javax.swing.JPanel your_bill;
    private javax.swing.JButton your_bill_del;
    private javax.swing.JPanel your_customer;
    private javax.swing.JPanel your_staff;
    private javax.swing.JPanel your_staff1;
    // End of variables declaration//GEN-END:variables
}
