
package medical_store_;
import java.sql.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.*;
import java.util.Date;
import java.time.*;

/**
 *
 * @author Ajay
 */
public class New_medicine extends javax.swing.JFrame {

    /**
     * Creates new form New_medicine
     */
    public Statement stmt;
        public ResultSet rs;
        public Connection con;
        public New_medicine() {
        try{  
            Class.forName("com.mysql.jdbc.Driver"); 
            }
        catch(Exception e){ System.out.println(e);}  

        initComponents();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        med_price = new javax.swing.JTextField();
        med_drug_name = new javax.swing.JTextField();
        med_trade_name = new javax.swing.JTextField();
        med_use = new javax.swing.JTextField();
        med_type = new javax.swing.JTextField();
        med_valid = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        med_submit = new javax.swing.JButton();
        med_company = new javax.swing.JTextField();
        med_quantity = new javax.swing.JSpinner();
        med_mfd = new javax.swing.JFormattedTextField();
        med_expd = new javax.swing.JFormattedTextField();
        med_done = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Register Medicine");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Drug Name* :");
        jLabel1.setToolTipText("");

        med_price.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_price.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        med_price.setToolTipText("");
        med_price.setMargin(new java.awt.Insets(2, 20, 2, 10));
        med_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_priceActionPerformed(evt);
            }
        });

        med_drug_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_drug_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        med_drug_name.setToolTipText("");
        med_drug_name.setMargin(new java.awt.Insets(2, 20, 2, 10));
        med_drug_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_drug_nameActionPerformed(evt);
            }
        });

        med_trade_name.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_trade_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        med_trade_name.setToolTipText("");
        med_trade_name.setMargin(new java.awt.Insets(2, 20, 2, 10));
        med_trade_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_trade_nameActionPerformed(evt);
            }
        });

        med_use.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_use.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        med_use.setToolTipText("");
        med_use.setMargin(new java.awt.Insets(2, 20, 2, 10));
        med_use.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_useActionPerformed(evt);
            }
        });

        med_type.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_type.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        med_type.setToolTipText("");
        med_type.setMargin(new java.awt.Insets(2, 20, 2, 10));
        med_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_typeActionPerformed(evt);
            }
        });

        med_valid.setForeground(new java.awt.Color(255, 0, 0));
        med_valid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        med_valid.setText("adjk");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Trade Name :");
        jLabel3.setToolTipText("");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Price* :");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Use :");
        jLabel5.setToolTipText("");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Quantity* :");
        jLabel6.setToolTipText("");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Mfd (DD/MM/YYYY)* :");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Expd (DD/MM/YYYY)* :");
        jLabel8.setToolTipText("");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Type* :");
        jLabel9.setToolTipText("");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Company Name* :");
        jLabel10.setToolTipText("");

        med_submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_submit.setText("Submit");
        med_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_submitActionPerformed(evt);
            }
        });

        med_company.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        med_company.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        med_company.setToolTipText("");
        med_company.setMargin(new java.awt.Insets(2, 20, 2, 10));
        med_company.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_companyActionPerformed(evt);
            }
        });

        med_quantity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        try {
            med_mfd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        med_mfd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        med_mfd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        med_mfd.setMargin(new java.awt.Insets(2, 20, 2, 10));
        med_mfd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_mfdActionPerformed(evt);
            }
        });

        try {
            med_expd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        med_expd.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        med_expd.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        med_expd.setMargin(new java.awt.Insets(2, 20, 2, 10));
        med_expd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                med_expdActionPerformed(evt);
            }
        });

        med_done.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        med_done.setForeground(new java.awt.Color(0, 204, 0));
        med_done.setText("Medicine Added!!!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(med_done)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(med_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(med_company, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(med_use, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(med_trade_name, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(med_valid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(med_drug_name, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(med_price)
                            .addComponent(med_quantity)
                            .addComponent(med_mfd, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(med_expd, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(med_type))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(med_valid, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_drug_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_trade_name, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_use, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_price, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(med_quantity, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_mfd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_expd, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_type, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_company, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(med_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(med_done))
                .addGap(46, 46, 46))
        );

        med_valid.setVisible(false);
        med_done.setVisible(false);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void med_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_priceActionPerformed

    private void med_drug_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_drug_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_drug_nameActionPerformed

    private void med_trade_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_trade_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_trade_nameActionPerformed

    private void med_useActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_useActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_useActionPerformed

    private void med_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_typeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_typeActionPerformed

    private void med_companyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_companyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_companyActionPerformed

    private void med_mfdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_mfdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_mfdActionPerformed

    private void med_expdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_expdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_med_expdActionPerformed
    
    private int TextValidation(){
        
        med_valid.setVisible(false);
        med_done.setVisible(false);
        
        String name =  med_drug_name.getText();
        if(name == null || name.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Drug Name. cannot be blank.");
        return 0;
        }
        
        
        String price =  med_price.getText();
        if(price == null || price.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Price cannot be blank.");
        return 0;
        }
        try  
       {  
         int price_dummy = Integer.parseInt(price);  
       }  
       catch(NumberFormatException nfe)  
       {  
         med_valid.setVisible(true);
         med_valid.setText("Enter a valid price.");
         return 0;
       }
        
        int quantity=0;
        try
        {
            med_quantity.commitEdit();
            quantity =  (Integer)med_quantity.getValue();
        }
        catch(Exception e)
        {
            System.out.println(e);
            med_valid.setVisible(true);
            med_valid.setText("Enter a valid Quantity.");
            return 0;
        }
        
        
        if(quantity<0) {
        med_valid.setVisible(true);
        med_valid.setText("Quantity cannot be negative.");
        return 0;
        }
        
        
       String mfd =  med_mfd.getText();
        try  
       {  
         Date mfd_date=new SimpleDateFormat("dd/MM/yyyy").parse(mfd);
         if(mfd_date.after(java.sql.Date.valueOf(java.time.LocalDate.now()))){
             med_valid.setVisible(true);   
             med_valid.setText("Manufacture Date is After todays date.");
            return 0;
         }
       }  
       catch(Exception e)  
       {  
         System.out.println(e);
         med_valid.setVisible(true);
         med_valid.setText("Enter a valid Manufacture Date.");
         return 0;
       }
        
        String expd =  med_expd.getText();
        try  
       {  
         Date expd_date=new SimpleDateFormat("dd/MM/yyyy").parse(expd);
         if(expd_date.before(java.sql.Date.valueOf(java.time.LocalDate.now()))){
                med_valid.setVisible(true);
                med_valid.setText("Expiry Date is Before todays date.");
            return 0;
         }
       }  
       catch(Exception e)  
       {  
         med_valid.setText("Enter a valid Expiry Date.");
         System.out.println(e);
         med_valid.setVisible(true);
         return 0;
       }
        
        String type =  med_type.getText();
        if(type == null || type.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Medicine Type cannot be blank.");
        return 0;
        }
        
        String comp_name =  med_company.getText();
        if(comp_name == null || comp_name.isEmpty()) {
        med_valid.setVisible(true);
        med_valid.setText("Company Name cannot be blank.");
        return 0;
        }
        
        return 1;
    }
    
    private void med_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_med_submitActionPerformed
       if(TextValidation()==1)
       {
           String name =  med_drug_name.getText();
           String t_name =  med_trade_name.getText();
           String desc =  med_use.getText();
           String price =  med_price.getText();
           int quantity =  (Integer)med_quantity.getValue();
           String mfd =  med_mfd.getText(); 
           String expd =  med_expd.getText();
            
           String mfd_sql="";
           String expd_sql="";
            try  
            {  
              Date mfd_date=new SimpleDateFormat("dd/MM/yyyy").parse(mfd);
              Date expd_date=new SimpleDateFormat("dd/MM/yyyy").parse(expd);
              SimpleDateFormat dmyFormat = new SimpleDateFormat("yyyy-MM-dd");
              mfd_sql = dmyFormat.format(mfd_date);
              expd_sql = dmyFormat.format(expd_date);
            }  
            catch(Exception e)  
            {  
              System.out.println(e);
            }
            
            String type =  med_type.getText();
            String comp_name =  med_company.getText();
            
            try{
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/medical_store","root","root");
                stmt=con.createStatement();
                rs = stmt.executeQuery("select max(Product_id)+1 as id from medicine_list;");  
                String id="";
                while(rs.next())  
                {
                    id = rs.getString("id");
                }
                med_done.setVisible(true);
                stmt.executeUpdate("CALL Put_medicine("+id+",'"+name+"','"+t_name+ "','"+desc+"',"+price+","+quantity+",'"+mfd_sql+"','"+expd_sql+"','"+type+"','"+comp_name+"');");
                con.close();
                
            }catch(Exception e){ System.out.println(e);}

            med_drug_name.setText("");
            med_trade_name.setText("");
            med_use.setText("");
            med_price.setText("");
            med_quantity.setValue(0);
            med_mfd.setText("");
            med_expd.setText("");
            med_type.setText("");
            med_company.setText("");
         
            
       }
    }//GEN-LAST:event_med_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new New_medicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField med_company;
    private javax.swing.JLabel med_done;
    private javax.swing.JTextField med_drug_name;
    private javax.swing.JFormattedTextField med_expd;
    private javax.swing.JFormattedTextField med_mfd;
    private javax.swing.JTextField med_price;
    private javax.swing.JSpinner med_quantity;
    private javax.swing.JButton med_submit;
    private javax.swing.JTextField med_trade_name;
    private javax.swing.JTextField med_type;
    private javax.swing.JTextField med_use;
    private javax.swing.JLabel med_valid;
    // End of variables declaration//GEN-END:variables
}
